"""تعريفات أقسام النظام وربطها بالتبويبات الرئيسية."""

MODULES = {
    # ---- العمليات ----
    "quantities": {
        "title": "الكميات / ورقة التمتير",
        "table": "quantities",
        "section": "ops",
        "hub_hidden": True,
        "fields": [
            ("ticket_no", "رقم العطل", "ticket"),
            ("item_no", "رقم البند", "boq_item"),
            ("description", "وصف البند", "text"),
            ("unit", "الوحدة", "text"),
            ("qty", "الكمية", "number"),
            ("unit_price", "سعر الوحدة", "number"),
            ("ref", "صورة/مرجع", "text"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["ticket_no", "item_no", "description", "unit", "qty", "unit_price"],
    },
    "photos": {
        "title": "قائمة الصور",
        "table": "photos",
        "section": "ops",
        "hub_hidden": True,
        "fields": [
            ("ticket_no", "رقم العطل", "ticket"),
            ("before_shot", "قبل التنفيذ", "image"),
            ("during_shot", "أثناء التنفيذ", "image"),
            ("after_shot", "بعد التنفيذ", "image"),
            ("quantities_shot", "صورة الكميات", "image"),
            ("location_shot", "صورة الموقع", "image"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["ticket_no", "before_shot", "during_shot", "after_shot", "quantities_shot", "location_shot"],
    },
    "metering": {
        "title": "التمتير",
        "table": "metering",
        "section": "ops",
        "hub_hidden": True,
        "fields": [
            ("ticket_no", "رقم العطل", "ticket"),
            ("officer", "مسؤول المستخلصات", "list:invoice_officers"),
            ("start_date", "تاريخ بداية التمتير", "date"),
            ("submit_date", "تاريخ رفع للاستشاري", "date"),
            ("approve_date", "تاريخ الاعتماد", "date"),
            ("status", "الحالة", "list:metering_status"),
            ("approved_value", "قيمة معتمدة (مبلغ الكميات)", "number"),
            ("reject_ratio", "نسبة رفض", "number"),
            ("notes", "ملاحظات الاستشاري", "textarea"),
        ],
        "list_cols": ["ticket_no", "officer", "start_date", "status", "approved_value"],
    },
    "invoices": {
        "title": "المستخلصات و SAP",
        "table": "invoices",
        "section": "financial",
        "fields": [
            ("invoice_id", "رقم المستخلص", "text"),
            ("ticket_no", "رقم العطل", "ticket"),
            ("period", "الفترة", "text"),
            ("value", "قيمة المستخلص", "number"),
            ("support_date", "تاريخ الرفع للمساندة", "date"),
            ("work_order", "رقم أمر العمل", "text"),
            ("work_order_date", "تاريخ أمر العمل", "date"),
            ("invoice_no", "رقم الفاتورة", "text"),
            ("invoice_date", "تاريخ الفاتورة", "date"),
            ("sap_date", "تاريخ رفع SAP", "date"),
            ("sap_status", "حالة SAP", "list:sap_status"),
            ("due_date", "تاريخ السداد المتوقع", "date"),
            ("paid_date", "تاريخ السداد الفعلي", "date"),
            ("collected", "المبلغ المحصل", "number"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["invoice_id", "ticket_no", "work_order", "period", "value", "sap_status", "collected"],
    },
    # ---- المقاولين ----
    "contractor_works": {
        "title": "أعمال المقاولين",
        "table": "contractor_works",
        "section": "contractors",
        "fields": [
            ("work_no", "رقم المعاملة", "text"),
            ("work_date", "التاريخ", "date"),
            ("contractor", "المقاول", "text"),
            ("ticket_no", "رقم العطل", "ticket"),
            ("work_type", "نوع العمل", "list:construction_types"),
            ("site", "الموقع", "text"),
            ("status", "الحالة", "list:execution_status"),
            ("value", "القيمة", "number"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["work_no", "work_date", "contractor", "ticket_no", "work_type", "status", "value"],
    },
    "contractor_supplies": {
        "title": "مواد موردة من مقاول",
        "table": "contractor_supplies",
        "section": "contractors",
        "fields": [
            ("supply_no", "رقم التوريد", "text"),
            ("supply_date", "التاريخ", "date"),
            ("contractor", "المقاول", "text"),
            ("ticket_no", "رقم العطل", "ticket"),
            ("work_no", "رقم معاملة المقاول", "text"),
            ("status", "الحالة", "list:contractor_supply_status"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["supply_no", "supply_date", "contractor", "ticket_no", "status"],
    },
    # ---- الإنشاءات ----
    "construction_works": {
        "title": "أعمال الإنشاءات",
        "table": "construction_works",
        "section": "constructions",
        "fields": [
            ("work_no", "رقم المعاملة", "text"),
            ("work_date", "التاريخ", "date"),
            ("site", "الموقع", "text"),
            ("district", "الحي", "text"),
            ("work_type", "نوع العمل", "list:construction_types"),
            ("station_no", "رقم المحطة", "text"),
            ("ticket_no", "رقم العطل المرتبط", "ticket"),
            ("status", "الحالة", "list:execution_status"),
            ("supervisor", "المشرف", "text"),
            ("value", "القيمة التقديرية", "number"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["work_no", "work_date", "site", "work_type", "ticket_no", "status", "value"],
    },
    # أوامر عمل الكهرباء (الفرق الأولية) — منفصلة عن الأعطال
    "primary_team_orders": {
        "title": "الفرق الأولية",
        "table": "primary_team_orders",
        "section": "ops",
        "hub_hidden": True,
        "fields": [
            ("work_order", "أمر العمل", "text"),
            ("extract_no", "رقم المستخلص", "text"),
            ("amount", "المبلغ", "number"),
            ("order_date", "التاريخ", "date"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["work_order", "extract_no", "amount", "order_date"],
    },
    # ---- المشاريع ----
    "projects": {
        "title": "المشاريع",
        "table": "projects",
        "section": "projects",
        "fields": [
            ("project_code", "كود المشروع", "text"),
            ("project_name", "اسم المشروع", "text"),
            ("project_type", "نوع المشروع", "list:project_types"),
            ("status", "الحالة", "list:project_status"),
            ("start_date", "تاريخ البداية", "date"),
            ("end_date", "تاريخ النهاية", "date"),
            ("ticket_no", "رقم العطل المرتبط", "ticket"),
            ("site", "الموقع", "text"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["project_code", "project_name", "project_type", "status", "start_date", "ticket_no"],
    },
    # ---- دليل البنود (مرآة للدليل النشط من رفع Excel في العقود) ----
    "boq_items": {
        "title": "دليل بنود العقد",
        "table": "boq_items",
        "section": "contracts",
        "fields": [
            ("item_no", "رقم البند", "text"),
            ("line_type", "نوع البند", "text"),
            ("short_desc", "التوصيف المختصر", "text"),
            ("long_desc", "التوصيف الكامل", "textarea"),
            ("description", "الوصف (متوافق)", "text"),
            ("unit", "الوحدة", "text"),
            ("unit_price", "سعر الوحدة", "number"),
            ("currency", "العملة", "text"),
            ("payment_type", "نوع الدفع", "text"),
            ("category", "التصنيف", "text"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["item_no", "short_desc", "unit", "unit_price", "currency", "line_type"],
    },
    # ---- التنسيقات والجودة ----
    "coordination": {
        "title": "التنسيقات الفنية",
        "table": "coordination",
        "section": "quality",
        "hub_hidden": True,
        "fields": [
            ("ticket_no", "رقم العطل", "ticket"),
            ("needs_asphalt", "هل يحتاج إخلاء أسفلت؟", "yesno"),
            ("officer", "مسؤول التنسيقات", "list:coordination_officers"),
            ("request_date", "تاريخ الطلب", "date"),
            ("lab", "المختبر", "text"),
            ("report_no", "رقم التقرير", "text"),
            ("receive_date", "تاريخ الاستلام", "date"),
            ("status", "الحالة", "list:coordination_status"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["ticket_no", "needs_asphalt", "officer", "request_date", "status"],
    },
    "quality_clearances": {
        "title": "إخلاءات الأسفلت (فسوحات)",
        "table": "quality_clearances",
        "section": "quality",
        "hub_hidden": True,
        "fields": [
            ("ticket_no", "رقم العطل", "ticket"),
            ("clearance_no", "رقم الإخلاء", "text"),
            ("rekaz_code", "كود ركاز (RR)", "text"),
            ("clearance_stage", "مرحلة الإخلاء", "list:clearance_stage"),
            ("request_date", "تاريخ الطلب", "date"),
            ("issue_date", "تاريخ الإصدار", "date"),
            ("contractor", "الجهة", "text"),
            ("status", "الحالة", "list:clearance_status"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["ticket_no", "rekaz_code", "clearance_no", "clearance_stage", "request_date", "status"],
    },
    "quality_inspections": {
        "title": "فحوصات الجودة",
        "table": "quality_inspections",
        "section": "quality",
        "hub_hidden": True,
        "fields": [
            ("ticket_no", "رقم العطل", "ticket"),
            ("inspect_date", "تاريخ الفحص", "date"),
            ("inspector", "المفتش", "text"),
            ("result", "النتيجة", "list:inspect_result"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["ticket_no", "inspect_date", "inspector", "result"],
    },
    # ---- التنسيقات الجديدة (داخل التنسيقات والجودة) ----
    "new_coordinations": {
        "title": "التنسيقات الجديدة",
        "table": "new_coordinations",
        "section": "quality",
        "hub_hidden": True,
        "fields": [
            ("coord_no", "رقم التنسيق", "text"),
            ("coord_kind", "نوع التبويب", "list:new_coord_kind"),
            ("request_date", "تاريخ الطلب", "date"),
            ("authority", "الجهة", "text"),
            ("work_desc", "وصف العمل", "text"),
            ("location", "الموقع", "text"),
            ("district", "الحي", "text"),
            ("linked_section", "القسم المستهدف بعد الإصدار", "list:linked_sections"),
            ("ticket_no", "رقم العطل (عمليات)", "ticket"),
            ("project_code", "كود المشروع", "text"),
            ("construction_work_no", "رقم معاملة الإنشاءات", "text"),
            ("status", "الحالة", "list:new_coord_status"),
            ("license_no", "رقم الرخصة", "text"),
            ("issue_date", "تاريخ الإصدار", "date"),
            ("expiry_date", "تاريخ الانتهاء", "date"),
            ("officer", "المسؤول", "text"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": [
            "coord_no",
            "coord_kind",
            "request_date",
            "authority",
            "linked_section",
            "ticket_no",
            "project_code",
            "construction_work_no",
            "status",
            "license_no",
        ],
    },
    "issued_licenses": {
        "title": "الرخص المصدرة",
        "table": "issued_licenses",
        "section": "quality",
        "hub_hidden": True,
        "fields": [
            ("license_no", "رقم الرخصة", "text"),
            ("rtc_no", "رقم رسملة / RTC", "text"),
            ("work_order", "أمر العمل", "text"),
            ("issue_date", "تاريخ الإصدار", "date"),
            ("expiry_date", "تاريخ الانتهاء", "date"),
            ("authority", "الجهة", "text"),
            ("license_type", "نوع الرخصة", "list:license_types"),
            ("status", "الحالة", "list:issued_license_status"),
            ("workflow_status", "متابعة التصريح", "list:license_workflow"),
            ("linked_section", "القسم المرتبط", "list:linked_sections"),
            ("ticket_no", "رقم العطل (عمليات)", "ticket"),
            ("project_code", "كود المشروع", "text"),
            ("construction_work_no", "رقم معاملة الإنشاءات", "text"),
            ("district", "الحي", "text"),
            ("location", "الموقع", "text"),
            ("license_length", "طول الرخصة", "number"),
            ("work_desc", "وصف العمل", "text"),
            ("consultant_submitted", "تقديم الاستشاري", "yesno"),
            ("consultant_submit_date", "تاريخ تقديم الاستشاري", "date"),
            ("consultant_result", "نتيجة الاستشاري", "list:consultant_result"),
            ("consultant_notes", "ملاحظات الاستشاري", "textarea"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": [
            "license_no",
            "rtc_no",
            "work_order",
            "issue_date",
            "expiry_date",
            "district",
            "workflow_status",
            "linked_section",
            "ticket_no",
            "status",
        ],
    },
    # ---- السلامة ----
    "safety_permits": {
        "title": "تصاريح العمل",
        "table": "safety_permits",
        "section": "safety",
        "fields": [
            ("permit_no", "رقم التصريح", "text"),
            ("ticket_no", "رقم العطل", "ticket"),
            ("work_order", "أمر العمل", "text"),
            ("permit_date", "التاريخ", "date"),
            ("location", "الموقع", "text"),
            ("issuer", "المُصدر", "text"),
            ("receiver", "المستلم", "text"),
            ("work_desc", "وصف العمل", "text"),
            ("status", "الحالة", "list:permit_status"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["permit_no", "ticket_no", "work_order", "permit_date", "location", "status"],
    },
    "safety_incidents": {
        "title": "بلاغات السلامة",
        "table": "safety_incidents",
        "section": "safety",
        "fields": [
            ("incident_no", "رقم العطل", "text"),
            ("incident_date", "التاريخ", "date"),
            ("location", "الموقع", "text"),
            ("incident_type", "نوع الحادث", "list:incident_types"),
            ("severity", "الخطورة", "list:severity_levels"),
            ("status", "الحالة", "list:execution_status"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["incident_no", "incident_date", "location", "incident_type", "severity", "status"],
    },
    # ---- المستودعات ----
    "warehouse_items": {
        "title": "أصناف المستودع",
        "table": "warehouse_items",
        "section": "warehouses",
        "hub_hidden": True,
        "fields": [
            ("item_no", "رقم المادة", "text"),
            ("item_name", "اسم المادة", "text"),
            ("unit", "الوحدة", "text"),
            ("category", "التصنيف", "list:warehouse_categories"),
            ("min_qty", "حد أدنى", "number"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["item_no", "item_name", "unit", "category", "min_qty"],
    },
    "warehouse_tx": {
        "title": "معاملات المستودع",
        "table": "warehouse_tx",
        "section": "warehouses",
        "hub_hidden": True,
        "fields": [
            ("voucher_no", "رقم السند", "text"),
            ("tx_date", "تاريخ الحركة", "date"),
            ("tx_type", "نوع الحركة", "list:warehouse_tx_types"),
            ("item_no", "رقم المادة", "warehouse_item"),
            ("item_name", "اسم المادة", "text"),
            ("unit", "الوحدة", "text"),
            ("qty", "الكمية", "number"),
            ("recipient", "المستلم", "text"),
            ("sender", "المسلم", "text"),
            ("ticket_no", "رقم العطل / كود ER", "ticket"),
            ("rekaz_code", "كود ركاز (ER)", "text"),
            ("source_section", "القسم المصدر", "text"),
            ("work_order", "رقم أمر العمل", "text"),
            ("source_ref", "مرجع المعاملة", "text"),
            ("region", "المنطقة", "text"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": [
            "voucher_no",
            "tx_date",
            "tx_type",
            "work_order",
            "item_no",
            "item_name",
            "qty",
            "ticket_no",
            "source_section",
            "rekaz_code",
            "recipient",
            "sender",
        ],
    },
    # ---- المشتريات والعهد ----
    "external_purchases": {
        "title": "المشتريات الخارجية",
        "table": "external_purchases",
        "section": "external",
        "fields": [
            ("purchase_no", "رقم الطلب", "text"),
            ("purchase_date", "التاريخ", "date"),
            ("supplier", "المورد", "text"),
            ("status", "الحالة", "list:purchase_status"),
            ("ticket_no", "رقم العطل", "ticket"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["purchase_no", "purchase_date", "supplier", "status"],
    },
    "custody": {
        "title": "العهد",
        "table": "custody",
        "section": "external",
        "fields": [
            ("custody_no", "رقم العهدة", "text"),
            ("custody_date", "التاريخ", "date"),
            ("employee", "الموظف", "text"),
            ("item_name", "المادة / المعدة", "text"),
            ("qty", "الكمية", "number"),
            ("status", "الحالة", "list:custody_status"),
            ("return_date", "تاريخ الإرجاع", "date"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["custody_no", "custody_date", "employee", "item_name", "qty", "status"],
    },
    # ---- الورشة ----
    "workshop_cars": {
        "title": "السيارات",
        "table": "workshop_cars",
        "section": "maintenance",
        "fields": [
            ("plate_no", "رقم اللوحة", "text"),
            ("car_type", "النوع", "text"),
            ("driver", "السائق", "text"),
            ("team", "الفرقة", "list:teams"),
            ("status", "الحالة", "list:vehicle_status"),
            ("last_service", "آخر صيانة", "date"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["plate_no", "car_type", "driver", "team", "status", "last_service"],
    },
    "workshop_equipment": {
        "title": "المعدات",
        "table": "workshop_equipment",
        "section": "maintenance",
        "fields": [
            ("equip_no", "رقم المعدة", "text"),
            ("equip_name", "اسم المعدة", "text"),
            ("status", "الحالة", "list:equipment_status"),
            ("location", "الموقع", "text"),
            ("last_service", "آخر صيانة", "date"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["equip_no", "equip_name", "status", "location", "last_service"],
    },
    # ---- الموارد البشرية ----
    "hr_employees": {
        "title": "الموظفون",
        "table": "hr_employees",
        "section": "hr",
        "fields": [
            ("emp_no", "الرقم الوظيفي", "text"),
            ("full_name", "الاسم", "text"),
            ("job_title", "المسمى الوظيفي", "text"),
            ("department", "القسم", "list:hr_departments"),
            ("phone", "الجوال", "text"),
            ("status", "الحالة", "list:hr_status"),
            ("join_date", "تاريخ الالتحاق", "date"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["emp_no", "full_name", "job_title", "department", "phone", "status"],
    },
    # ---- العقود ----
    "contracts": {
        "title": "العقود",
        "table": "contracts",
        "section": "contracts",
        "fields": [
            ("contract_no", "رقم العقد", "text"),
            ("contract_name", "اسم العقد", "text"),
            ("party", "الجهة", "text"),
            ("start_date", "تاريخ البداية", "date"),
            ("end_date", "تاريخ النهاية", "date"),
            ("value", "قيمة العقد", "number"),
            ("status", "الحالة", "list:contract_status"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["contract_no", "contract_name", "party", "start_date", "end_date", "status"],
    },
    # ---- التعزيز - اسكيمات ----
    "reinforcement_departments": {
        "title": "أقسام التعزيز",
        "table": "reinforcement_departments",
        "section": "reinforcement",
        "fields": [
            ("dept_name", "اسم القسم", "text"),
            ("dept_code", "رمز القسم", "text"),
            ("status", "الحالة", "list:yes_no_active"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["dept_name", "dept_code", "status"],
    },
    "reinforcement_works": {
        "title": "معاملات التعزيز / اسكيمات",
        "table": "reinforcement_works",
        "section": "reinforcement",
        "fields": [
            ("work_no", "رقم المعاملة", "text"),
            ("work_date", "التاريخ", "date"),
            ("department", "القسم", "reinforcement_dept"),
            ("work_type", "نوع العمل", "text"),
            ("location", "الموقع", "text"),
            ("ticket_no", "رقم العطل", "ticket"),
            ("status", "الحالة", "list:execution_status"),
            ("value", "القيمة", "number"),
            ("notes", "ملاحظات", "textarea"),
        ],
        "list_cols": ["work_no", "work_date", "department", "work_type", "location", "status", "value"],
    },
}

SECTION_META = {
    "constructions": {"title": "الإنشاءات - التنفيذ", "home": "constructions_home"},
    "projects": {"title": "المشاريع", "home": "projects_home"},
    "ops": {"title": "العمليات والصيانة", "home": "ops_home"},
    "contractors": {"title": "المقاولين", "home": "contractors_home"},
    "quality": {"title": "التنسيقات والجودة", "home": "quality_home"},
    "safety": {"title": "السلامة", "home": "safety_home"},
    "warehouses": {"title": "المستودعات", "home": "warehouses_home"},
    "external": {"title": "المشتريات الخارجية والعهد", "home": "external_purchases_home"},
    "financial": {"title": "المتابعات المالية", "home": "financial_home"},
    "maintenance": {"title": "الورشة (سيارات - معدات)", "home": "maintenance_home"},
    "hr": {"title": "الموارد البشرية", "home": "hr_home"},
    "contracts": {"title": "إدارة العقود", "home": "contracts_admin_home"},
    "reinforcement": {"title": "التعزيز - اسكيمات", "home": "reinforcement_home"},
}


def modules_for_section(section, *, include_hidden: bool = False):
    return [
        (k, m)
        for k, m in MODULES.items()
        if m.get("section") == section and (include_hidden or not m.get("hub_hidden"))
    ]
