"""وجهات القفز السريع وخدمات مساعدة خفيفة للعمليات."""

from __future__ import annotations


def jump_destinations():
    """قائمة وجهات نافذة القفز السريع."""
    return [
        {"title": "الإنشاءات - التنفيذ", "path": "/constructions", "group": "أقسام", "keywords": "إنشاءات"},
        {"title": "التنسيقات الجديدة", "path": "/quality?tab=new_coords&sub=coords", "group": "التنسيقات والجودة", "keywords": "تنسيق رخصة إصدار"},
        {"title": "البلاغات", "path": "/quality?tab=new_coords&sub=reports", "group": "التنسيقات والجودة", "keywords": "بلاغ بلاغات"},
        {"title": "المخطط الشامل", "path": "/quality?tab=new_coords&sub=master_plan", "group": "التنسيقات والجودة", "keywords": "مخطط شامل"},
        {"title": "المخالفات", "path": "/quality?tab=new_coords&sub=violations", "group": "التنسيقات والجودة", "keywords": "مخالفة مخالفات"},
        {"title": "الرخص المنتهية", "path": "/quality?tab=new_coords&sub=expired", "group": "التنسيقات والجودة", "keywords": "رخص منتهية"},
        {"title": "الرخص الملغاة", "path": "/quality?tab=evacuations&sub=cancelled", "group": "التنسيقات والجودة", "keywords": "رخص ملغاة"},
        {"title": "الإخلاء النهائي", "path": "/quality?tab=evacuations&sub=final", "group": "التنسيقات والجودة", "keywords": "إخلاء نهائي"},
        {"title": "متابعة تصاريح العمل", "path": "/quality?tab=permits&sub=active", "group": "التنسيقات والجودة", "keywords": "رخص سارية تصاريح"},
        {"title": "الرخص السارية", "path": "/quality?tab=permits&sub=active", "group": "التنسيقات والجودة", "keywords": "رخص سارية"},
        {"title": "تحت التشييكات", "path": "/quality?tab=permits&sub=checks", "group": "التنسيقات والجودة", "keywords": "تشييكات"},
        {"title": "تحت إجراءات الإغلاق", "path": "/quality?tab=permits&sub=closing", "group": "التنسيقات والجودة", "keywords": "إغلاق"},
        {"title": "من هنا تبدأ رحلة الإخلاءات", "path": "/quality?tab=evacuations&sub=initial", "group": "التنسيقات والجودة", "keywords": "إخلاءات رحلة إغلاق"},
        {"title": "موردي الأسفلت", "path": "/quality?tab=permits&sub=asphalt", "group": "التنسيقات والجودة", "keywords": "أسفلت"},
        {"title": "الإخلاءات", "path": "/quality?tab=evacuations&sub=initial", "group": "التنسيقات والجودة", "keywords": "إخلاء أسفلت"},
        {"title": "الإخلاء المبدئي", "path": "/quality?tab=evacuations&sub=initial", "group": "التنسيقات والجودة", "keywords": "إخلاء مبدئي"},
        {"title": "الأعطال", "path": "/tickets", "group": "عمليات", "keywords": "عطل أعطال ticket fault طوارئ ops"},
        {"title": "عطل جديد", "path": "/tickets/new", "group": "عمليات", "keywords": "إضافة عطل جديد"},
        {"title": "فرق المهام", "path": "/teams", "group": "عمليات", "keywords": "فرقة فريق"},
        {"title": "الكميات (من داخل العطل)", "path": "/module/quantities", "group": "سجلات مرتبطة", "keywords": "كميات boq"},
        {"title": "قائمة الصور (من داخل العطل)", "path": "/module/photos", "group": "سجلات مرتبطة", "keywords": "صور"},
        {"title": "التمتير (من داخل العطل)", "path": "/module/metering", "group": "سجلات مرتبطة", "keywords": "تمتير مستخلص"},
        {"title": "المقاولين", "path": "/contractors", "group": "أقسام", "keywords": "مقاول"},
        {"title": "التعزيز - اسكيمات", "path": "/reinforcement", "group": "عمليات", "keywords": "تعزيز اسكيمات عدادات محطات ops"},
        {"title": "التنسيقات والجودة", "path": "/quality", "group": "أقسام", "keywords": "تنسيق جودة"},
        {"title": "السلامة", "path": "/safety", "group": "أقسام", "keywords": "سلامة تصريح"},
        {"title": "المستودعات", "path": "/warehouses", "group": "أقسام", "keywords": "مستودع مواد"},
        {"title": "مستودع الإنشاءات", "path": "/warehouses/constructions", "group": "أقسام", "keywords": "مستودع إنشاءات"},
        {"title": "مستودع العمليات", "path": "/warehouses/ops", "group": "أقسام", "keywords": "مستودع أعطال"},
        {"title": "مستودع المشاريع", "path": "/warehouses/projects", "group": "أقسام", "keywords": "مستودع مشاريع"},
        {"title": "أرصدة المواد", "path": "/warehouses/balances", "group": "أقسام", "keywords": "رصيد"},
        {"title": "المشتريات والعهد", "path": "/external-purchases", "group": "أقسام", "keywords": "شراء عهدة"},
        {"title": "المتابعات المالية", "path": "/financial", "group": "مالية", "keywords": "مالية مستخلص"},
        {"title": "المستخلصات و SAP", "path": "/module/invoices", "group": "مالية", "keywords": "فاتورة sap"},
        {"title": "المشاريع", "path": "/projects", "group": "أقسام", "keywords": "مشروع خاصة كهرباء"},
        {"title": "الورشة", "path": "/maintenance", "group": "أقسام", "keywords": "سيارة معدة ورشة"},
        {"title": "الموارد البشرية", "path": "/hr", "group": "أقسام", "keywords": "موظف موارد"},
        {"title": "إدارة العقود وبنود العقد", "path": "/contracts-admin", "group": "عقود", "keywords": "عقد بنود boq"},
        {"title": "دليل بنود العقد", "path": "/module/boq_items", "group": "عقود", "keywords": "بند عقد دليل"},
        {"title": "المستخدمون", "path": "/users/list", "group": "إدارة", "keywords": "مستخدم"},
        {"title": "سجل النشاط", "path": "/admin/audit-log/view", "group": "إدارة", "keywords": "سجل audit"},
        {"title": "البحث العام", "path": "/search", "group": "إدارة", "keywords": "بحث search"},
    ]
